name: Test prover core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/setup@v1
      with:
        version: 11
        package-json-file: webui/package.json
        install: false
    - name: Run Linter
      working-directory: ./webui
      run: pnpm install --frozen-lockfile && pnpm --filter app lint

    - name: Run unit tests
      run: cargo test --verbose --manifest-path fitch-proof/Cargo.toml
    - name: Run integration tests
      run: cargo test --verbose --manifest-path cli/Cargo.toml
